### ISSUE TITLE
 Java heap space Error only when there is a reducer in mapreduce

### ISSUE THREAD

**Issue by piccolbo** [RevolutionAnalytics/rmr2#148]
Originally reported [here](https://groups.google.com/forum/#!topic/rhadoop/-6Q1Pw3c1AA)

**Comment by ShashiGudur** [comment]
I tested ( on Horton works HDP 2.3.) I can only run rmr2 3.1.0 version the next two versions 3.2.0 and 3.3.0 and 3.3.1, I couldnt run it because i am getting Java heap space error only with reducer,
my  mapreduce.task.io.sort.mb = 64

system settings
Sys.setenv(HADOOP_HOME="/usr/hdp/current/hadoop-client")  #Its hadooop path
Sys.setenv(HADOOP_CMD="/usr/hdp/2.3.2.0-2950/hadoop/bin/hadoop") #It's CMD path
Sys.setenv(HADOOP_STREAMING="/usr/hdp/2.3.2.0-2950/hadoop-mapreduce/hadoop-streaming.jar") # It's streaming path
Sys.setenv(HADOOP_HEAPSIZE=2900)

following are my rmr settings

rmr.options.env = new.env(parent=emptyenv())

rmr.options.env$backend = "hadoop"
rmr.options.env$profile.nodes = "off"
rmr.options.env$hdfs.tempdir = "/tmp" #can't check it exists here
rmr.options.env$exclude.objects = NULL

rmr.options.env$backend.parameters =  
  list(
    hadoop = 
      list(cmdenv="PATH=/usr/local/lib64/R/bin/",
           D = "mapreduce.map.java.opts=-Xmx1024M", 
           D = "mapreduce.reduce.java.opts=-Xmx2048M",
           #D = "mapred.job.queue.name=other",
           D = "mapred.tasktracker.map.tasks.maximum",
           D = "mapred.tasktracker.reduce.tasks.maximum",
           D = "mapreduce.map.memory.mb = 5120",
           D = "mapreduce.reduce.memory.mb = 5120",
           D = "mapreduce.task.io.sort.mb =64",
           D = "yarn.scheduler.minimum-allocation.mb = 1000",
           D = "yarn.scheduler.maximum-allocation.mb = 2000"))

@derrickoswald :: were you able to run rmr2 3.2.0 or later versions without java heap space error? I tried all the version after 3.1.0 but my job fails at the reducer

Thanks
Shashi

**Comment by ShashiGudur** [comment]
@derrickoswald :: were able to run rmr2 3.2.0 or later versions without java heap space error? I tried all the version after 3.1.0 but my job fails at the reducer

Thanks
Shashi

**Comment by saargolde** [comment]
rmr2 V. 3.3.1 works on my HDP sandbox 2.3 without any problem, both with
the configuration you defined above and with my (much shorter) setup, which
includes:

Sys.setenv("HADOOP_CMD"="/usr/bin/hadoop")
Sys.setenv("HADOOP_STREAMING"="/usr/hdp/2.3.0.0-2557/hadoop-mapreduce/hadoop-streaming-2.7.1.2.3.0.0-2557.jar")

rmr.options(backend.parameters = list(
  hadoop = list(D = "mapreduce.map.memory.mb=1024")
))

It might be helpful to post your code and/or the error messages, because
the answers to the following questions matter:
- are the errors happening at the mapper or at the reducer?
- what kind of data format (input.format / output.format) are you using?
  some of them are surprisingly resource-hungry...

There may be more questions to ask, but that's a good start.

**Comment by ShashiGudur** [comment]
Here is the code and error

> rbingroups = rbinom(30, n = 50, prob = 0.5)
>  groups<-tapply(rbingroups, rbingroups, length)
> groups = to.dfs(rbingroups)
WARNING: Use "yarn jar" to launch YARN applications.
15/11/25 13:32:40 INFO zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
15/11/25 13:32:40 INFO compress.CodecPool: Got brand-new compressor [.deflate]
> rmr.options.env = new.env(parent=emptyenv())
> 
> rmr.options.env$backend = "hadoop"
> rmr.options.env$profile.nodes = "off"
> rmr.options.env$hdfs.tempdir = "/tmp" #can't check it exists here
> rmr.options.env$exclude.objects = NULL
> 
> 
> rmr.options.env$backend.parameters =  
+   list(
+     hadoop = 
+       list(cmdenv="PATH=/usr/local/lib64/R/bin/",
+            D = "mapreduce.map.java.opts=-Xmx1024M", 
+            D = "mapreduce.reduce.java.opts=-Xmx2048M",
+            #D = "mapred.job.queue.name=other",
+            D = "mapred.tasktracker.map.tasks.maximum",
+            D = "mapred.tasktracker.reduce.tasks.maximum",
+            D = "mapreduce.map.memory.mb = 5120",
+            D = "mapreduce.reduce.memory.mb = 5120",
+            D = "mapreduce.task.io.sort.mb =64",
+            D = "yarn.scheduler.minimum-allocation.mb = 1000",
+            D = "yarn.scheduler.maximum-allocation.mb = 2000"))
> rbingroups = rbinom(30, n = 50, prob = 0.5)
>  groups<-tapply(rbingroups, rbingroups, length)
> groups = to.dfs(rbingroups)
WARNING: Use "yarn jar" to launch YARN applications.
15/11/25 13:36:59 INFO zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
15/11/25 13:36:59 INFO compress.CodecPool: Got brand-new compressor [.deflate]
> out = mapreduce(input = groups,map = function(k,v) keyval(v, 1),reduce = function(k,vv) keyval(k, length(vv)))
WARNING: Use "yarn jar" to launch YARN applications.
packageJobJar: [] [/usr/hdp/2.3.2.0-2950/hadoop-mapreduce/hadoop-streaming-2.7.1.2.3.2.0-2950.jar] /tmp/streamjob6715154162749713919.jar tmpDir=null
15/11/25 13:37:18 INFO impl.TimelineClientImpl: Timeline service address: http://znlhacdq0003.amer.zurich.corp:8188/ws/v1/timeline/
15/11/25 13:37:18 INFO impl.TimelineClientImpl: Timeline service address: http://znlhacdq0003.amer.zurich.corp:8188/ws/v1/timeline/
15/11/25 13:37:18 INFO hdfs.DFSClient: Created HDFS_DELEGATION_TOKEN token 74288 for uszllf7 on ha-hdfs:ZHDPDEV
15/11/25 13:37:18 INFO security.TokenCache: Got dt for hdfs://ZHDPDEV; Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:ZHDPDEV, Ident: (HDFS_DELEGATION_TOKEN token 74288 for uszllf7)
15/11/25 13:37:20 INFO mapred.FileInputFormat: Total input paths to process : 1
15/11/25 13:37:20 INFO mapreduce.JobSubmitter: number of splits:2
15/11/25 13:37:20 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1447621077216_4452
15/11/25 13:37:20 INFO mapreduce.JobSubmitter: Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:ZHDPDEV, Ident: (HDFS_DELEGATION_TOKEN token 74288 for uszllf7)
15/11/25 13:37:21 INFO impl.YarnClientImpl: Submitted application application_1447621077216_4452
15/11/25 13:37:21 INFO mapreduce.Job: The url to track the job: http://znlhacdq0001.amer.zurich.corp:8088/proxy/application_1447621077216_4452/
15/11/25 13:37:21 INFO mapreduce.Job: Running job: job_1447621077216_4452
15/11/25 13:37:33 INFO mapreduce.Job: Job job_1447621077216_4452 running in uber mode : false
15/11/25 13:37:33 INFO mapreduce.Job:  map 0% reduce 0%
15/11/25 13:37:43 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000000_0, Status : FAILED
Error: Java heap space
15/11/25 13:37:43 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000001_0, Status : FAILED
Error: Java heap space
15/11/25 13:37:52 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000000_1, Status : FAILED
Error: Java heap space
15/11/25 13:37:53 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000001_1, Status : FAILED
Error: Java heap space
15/11/25 13:37:57 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000000_2, Status : FAILED
Error: Java heap space
15/11/25 13:37:58 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000001_2, Status : FAILED
Error: Java heap space
15/11/25 13:38:03 INFO mapreduce.Job:  map 100% reduce 100%
15/11/25 13:38:03 INFO mapreduce.Job: Job job_1447621077216_4452 failed with state FAILED due to: Task failed task_1447621077216_4452_m_000000
Job failed as tasks failed. failedMaps:1 failedReduces:0

15/11/25 13:38:03 INFO mapreduce.Job: Counters: 13
	Job Counters 
		Failed map tasks=7
		Killed map tasks=1
		Launched map tasks=8
		Other local map tasks=6
		Data-local map tasks=2
		Total time spent by all maps in occupied slots (ms)=44129
		Total time spent by all reduces in occupied slots (ms)=0
		Total time spent by all map tasks (ms)=44129
		Total vcore-seconds taken by all map tasks=44129
		Total megabyte-seconds taken by all map tasks=451880960
	Map-Reduce Framework
		CPU time spent (ms)=0
		Physical memory (bytes) snapshot=0
		Virtual memory (bytes) snapshot=0
15/11/25 13:38:03 ERROR streaming.StreamJob: Job not successful!
Streaming Command Failed!
Error in mr(map = map, reduce = reduce, combine = combine, vectorized.reduce,  : 
  hadoop streaming failed with error code 1
15/11/25 13:38:12 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 3600 minutes, Emptier interval = 0 minutes.
Moved: 'hdfs://ZHDPDEV/tmp/file113f63ecb6cc' to trash at: hdfs://ZHDPDEV/user/uszllf7/.Trash/Current
15/11/25 13:38:19 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 3600 minutes, Emptier interval = 0 minutes.
Moved: 'hdfs://ZHDPDEV/tmp/file113f7614dedf' to trash at: hdfs://ZHDPDEV/user/uszllf7/.Trash/Current

**Comment by ShashiGudur** [comment]
Here is the code and error

if I only use map function it works perfect and fails when I use reducer or map reduce together

---

> rbingroups = rbinom(30, n = 50, prob = 0.5)
>  groups<-tapply(rbingroups, rbingroups, length)
> groups = to.dfs(rbingroups)
> WARNING: Use "yarn jar" to launch YARN applications.
> 15/11/25 13:32:40 INFO zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
> 15/11/25 13:32:40 INFO compress.CodecPool: Got brand-new compressor [.deflate]
> rmr.options.env = new.env(parent=emptyenv())
> 
> rmr.options.env$backend = "hadoop"
> rmr.options.env$profile.nodes = "off"
> rmr.options.env$hdfs.tempdir = "/tmp" #can't check it exists here
> rmr.options.env$exclude.objects = NULL
> 
> rmr.options.env$backend.parameters =  
> -   list(
> -     hadoop = 
> -       list(cmdenv="PATH=/usr/local/lib64/R/bin/",
> -            D = "mapreduce.map.java.opts=-Xmx1024M", 
> -            D = "mapreduce.reduce.java.opts=-Xmx2048M",
> -            #D = "mapred.job.queue.name=other",
> -            D = "mapred.tasktracker.map.tasks.maximum",
> -            D = "mapred.tasktracker.reduce.tasks.maximum",
> -            D = "mapreduce.map.memory.mb = 5120",
> -            D = "mapreduce.reduce.memory.mb = 5120",
> -            D = "mapreduce.task.io.sort.mb =64",
> -            D = "yarn.scheduler.minimum-allocation.mb = 1000",
> -            D = "yarn.scheduler.maximum-allocation.mb = 2000"))
>   rbingroups = rbinom(30, n = 50, prob = 0.5)
>   groups<-tapply(rbingroups, rbingroups, length)
>   groups = to.dfs(rbingroups)
>   WARNING: Use "yarn jar" to launch YARN applications.
>   15/11/25 13:36:59 INFO zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
>   15/11/25 13:36:59 INFO compress.CodecPool: Got brand-new compressor [.deflate]
>   out = mapreduce(input = groups,map = function(k,v) keyval(v, 1),reduce = function(k,vv) keyval(k, length(vv)))
>   WARNING: Use "yarn jar" to launch YARN applications.
>   packageJobJar: [] [/usr/hdp/2.3.2.0-2950/hadoop-mapreduce/hadoop-streaming-2.7.1.2.3.2.0-2950.jar] /tmp/streamjob6715154162749713919.jar tmpDir=null
>   15/11/25 13:37:18 INFO impl.TimelineClientImpl: Timeline service address: http://znlhacdq0003.amer.zurich.corp:8188/ws/v1/timeline/
>   15/11/25 13:37:18 INFO impl.TimelineClientImpl: Timeline service address: http://znlhacdq0003.amer.zurich.corp:8188/ws/v1/timeline/
>   15/11/25 13:37:18 INFO hdfs.DFSClient: Created HDFS_DELEGATION_TOKEN token 74288 for uszllf7 on ha-hdfs:ZHDPDEV
>   15/11/25 13:37:18 INFO security.TokenCache: Got dt for hdfs://ZHDPDEV; Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:ZHDPDEV, Ident: (HDFS_DELEGATION_TOKEN token 74288 for uszllf7)
>   15/11/25 13:37:20 INFO mapred.FileInputFormat: Total input paths to process : 1
>   15/11/25 13:37:20 INFO mapreduce.JobSubmitter: number of splits:2
>   15/11/25 13:37:20 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1447621077216_4452
>   15/11/25 13:37:20 INFO mapreduce.JobSubmitter: Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:ZHDPDEV, Ident: (HDFS_DELEGATION_TOKEN token 74288 for uszllf7)
>   15/11/25 13:37:21 INFO impl.YarnClientImpl: Submitted application application_1447621077216_4452
>   15/11/25 13:37:21 INFO mapreduce.Job: The url to track the job: http://znlhacdq0001.amer.zurich.corp:8088/proxy/application_1447621077216_4452/
>   15/11/25 13:37:21 INFO mapreduce.Job: Running job: job_1447621077216_4452
>   15/11/25 13:37:33 INFO mapreduce.Job: Job job_1447621077216_4452 running in uber mode : false
>   15/11/25 13:37:33 INFO mapreduce.Job:  map 0% reduce 0%
>   15/11/25 13:37:43 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000000_0, Status : FAILED
>   Error: Java heap space
>   15/11/25 13:37:43 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000001_0, Status : FAILED
>   Error: Java heap space
>   15/11/25 13:37:52 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000000_1, Status : FAILED
>   Error: Java heap space
>   15/11/25 13:37:53 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000001_1, Status : FAILED
>   Error: Java heap space
>   15/11/25 13:37:57 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000000_2, Status : FAILED
>   Error: Java heap space
>   15/11/25 13:37:58 INFO mapreduce.Job: Task Id : attempt_1447621077216_4452_m_000001_2, Status : FAILED
>   Error: Java heap space
>   15/11/25 13:38:03 INFO mapreduce.Job:  map 100% reduce 100%
>   15/11/25 13:38:03 INFO mapreduce.Job: Job job_1447621077216_4452 failed with state FAILED due to: Task failed task_1447621077216_4452_m_000000
>   Job failed as tasks failed. failedMaps:1 failedReduces:0

15/11/25 13:38:03 INFO mapreduce.Job: Counters: 13
    Job Counters 
        Failed map tasks=7
        Killed map tasks=1
        Launched map tasks=8
        Other local map tasks=6
        Data-local map tasks=2
        Total time spent by all maps in occupied slots (ms)=44129
        Total time spent by all reduces in occupied slots (ms)=0
        Total time spent by all map tasks (ms)=44129
        Total vcore-seconds taken by all map tasks=44129
        Total megabyte-seconds taken by all map tasks=451880960
    Map-Reduce Framework
        CPU time spent (ms)=0
        Physical memory (bytes) snapshot=0
        Virtual memory (bytes) snapshot=0
15/11/25 13:38:03 ERROR streaming.StreamJob: Job not successful!
Streaming Command Failed!
Error in mr(map = map, reduce = reduce, combine = combine, vectorized.reduce,  : 
  hadoop streaming failed with error code 1
15/11/25 13:38:12 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 3600 minutes, Emptier interval = 0 minutes.
Moved: 'hdfs://ZHDPDEV/tmp/file113f63ecb6cc' to trash at: hdfs://ZHDPDEV/user/uszllf7/.Trash/Current
15/11/25 13:38:19 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 3600 minutes, Emptier interval = 0 minutes.
Moved: 'hdfs://ZHDPDEV/tmp/file113f7614dedf' to trash at: hdfs://ZHDPDEV/user/uszllf7/.Trash/Current

**Comment by saargolde** [comment]
Try with my setup (detailed up in this thread), and if that doesn't work,
try re-installing. It's a mystery...
